### ISSUE TITLE
Signed cfg.bin can't be read

### ISSUE THREAD

**Issue by leineg** [Tiniifan/Nyanko#1]
Apparently cfg.bin files from this game don't work on Nyanko, is this normal?

**Comment by Tiniifan** [comment]
Yes the problem is due to the fact that cfg.bin on IEGO2 uses a signature that isn't recognized by the cfgbin reader in this version of nyanko.

**Comment by Tiniifan** [comment]
I think the problem has been solved, try the [latest version](https://github.com/Tiniifan/Nyanko/releases/tag/1.1.0.1)

**Comment by leineg** [comment]
Yes it works thanks man.
